name: Daily
on:
  schedule:
  - cron: "55 23 * * *"
jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Ingests data from Discord
        run: |
          python3 -m pip install -r requirements.txt
          GOOGLE_SERVICE_ACCOUNT=${{ secrets.GOOGLE_SERVICE_ACCOUNT }} python3 generate_service_account.py
          DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }} python3 main.py
          curl -XGET '${{ secrets.HEALTHCHECK }}'
