name: CI
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Lints
        run: |
          python3 -m pip install -r requirements.txt
          flake8 main.py generate_service_account.py